# Generated by Django 2.1.1 on 2018-09-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20180918_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='superuser',
        ),
    ]
