# Generated by Django 2.1.1 on 2018-09-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='')),
                ('product_desc', models.TextField()),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product_Category')),
            ],
        ),
    ]
